### ISSUE TITLE
Understanding use cases

### ISSUE THREAD

**Issue by Correct-Syntax** [sander76/aio_wx_widgets#1]
Hi @sander76,

This is a neat-looking project. I was wondering what exactly are the use-cases for this lib? I ran the demo and browsed the code, but I was wondering if you could explain how this library would be useful in a program. I understand in has an MVC architecture, but is it just for writing wxpython in a MVC way or does it do more than that?

Thank you for your time.

**Comment by sander76** [comment]
Hi @Correct-Syntax 

I created this library -like you suspect- for usage of wxpython in a MVC like pattern.
The widgets are wrapping wx-widgets in an optinionated way and I have added databinding as this greatly reduced boilerplate.

That's it basically...

**Comment by Correct-Syntax** [comment]
Okay. MVC is good. Why so many dependencies, though?

**Comment by sander76** [comment]
It is opinionated and uses dependencies which make sense to me. But feel free do improve on this.
